In [2]:
from array import *
arr=array('i',[1,2,3,4])
print(arr)


array('i', [1, 2, 3, 4])


In [3]:
from numpy import *
arr=arange(20,41)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [18]:
fives=ones(10)*5
print(fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [19]:
from numpy import *
random.seed(12)
arr1=random.randint(1,56,24).reshape(3,4,2)
arr=arange(20,29).reshape(3,3)
print(arr1)
print(arr)

[[[12 28]
  [ 7 50]
  [ 3  4]
  [ 4 13]]

 [[49 23]
  [50 53]
  [ 6 14]
  [26 35]]

 [[12 55]
  [11  1]
  [54 41]
  [13 14]]]
[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [12]:
from numpy import *
random.seed(12)
arr=random.randint(0,2,24).reshape(2,-1)
print(arr)

[[1 1 0 1 1 0 1 1 0 0 0 1]
 [0 1 1 1 0 1 0 0 0 1 0 0]]


In [22]:
from numpy import *
random.seed(12)
arr=random.randint(1,100,20)
arr[arr%2==0]=-1
print(arr)

[-1 -1  7  3 -1 -1 77 49 23 -1 53 -1 -1 -1 35 -1 75  1 77 -1]
