In [3]:
# BAsic array syntax
from array import *
arr=array('i',[])
n=int(input())
for i in range(n):
    x=int(input())
    arr.append(x)
print(arr)

5
1
2
3
4
5
array('i', [1, 2, 3, 4, 5])


In [34]:
# Basic practics
from numpy import *
num=[1,2,3,4,5,6,7,8,9]
num=array(num)
m=num.reshape(3,3)
print(diagonal(m))
print(m)

[1 5 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# Create numpy array
num=[[1,2,3],[4,5,6]]
num=array(num)
print(num)
print(num.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [76]:
# Reshapping of data
from numpy import *
# ran_arr=random.randint(1,100,20)
# ran_arr=ran_arr.reshape(4,5)
# print(ran_arr)
arr=arange(1,11)
arr=arr.reshape(5,-1)
print(arr)



[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [98]:
#Seed function()
from numpy import *
random.seed(5)          # number does not chnage after executing multiple time
arr=random.randint(1,100,20)
print(arr.size)



20


In [110]:
# Indexing and Slicing of 1_d array
arr=arange(1,11)
print(arr[-3])
print(arr[3:6])      # slicing
print(arr[:2])

8
[4 5 6]
[1 2]


In [154]:
# Indexing and slicing of 2d array
arr=arange(1,21)
arr=arr.reshape(4,5)
m=matrix(arr) 
print(m)
print(m[1:3,1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]


In [4]:
#view and copy function
from numpy import *
arr=array([1,5,4,7,8,3])
slic_arr=arr[2:5]
slic_arr[:]=0
print(slic_arr)
print(arr)

[0 0 0]
[1 5 0 0 0 3]


In [12]:
# Condtional selection
from numpy import *
arr=arange(1,11)
max=arr[arr%2==0]
print(arr[arr<4])
print(max)

[1 2 3]
[ 2  4  6  8 10]


In [16]:
# operation on array
from numpy import *
arr=array([1,4,7,9])
print(arr*2)
print(arr+5)
print(arr**2)

[ 2  8 14 18]
[ 6  9 12 14]
[ 1 16 49 81]


In [19]:
from numpy import *
random.seed(123)
matrix1=random.randint(1,12,9).reshape(3,3)
matrix2=random.randint(30,40,9).reshape(3,3)
print(matrix1.dot(matrix2))
print()

[[411 421 444]
 [543 556 564]
 [576 588 723]]



In [27]:
from numpy import *
random.seed(123)
arr=random.randint(1,20,9).reshape(3,3)
print(arr)
print(sqrt(arr))
print(exp(arr))
print(arr.min())
print(arr.max())
print(arr.diagonal())

[[14  3  3]
 [ 7 18 11]
 [ 2  1 18]]
[[3.74165739 1.73205081 1.73205081]
 [2.64575131 4.24264069 3.31662479]
 [1.41421356 1.         4.24264069]]
[[1.20260428e+06 2.00855369e+01 2.00855369e+01]
 [1.09663316e+03 6.56599691e+07 5.98741417e+04]
 [7.38905610e+00 2.71828183e+00 6.56599691e+07]]
1
18
[14 18 18]


In [35]:
# Axis tutorials
from numpy import *
random.seed(123)
arr=random.randint(1,11,9).reshape(3,3)
print(arr)
# print(sum(arr))
# print(arr.sum())
print(arr.min(axis=1))
print(arr.min(axis=0))
print(arr.sum(axis=1))
print(arr.prod(axis=1))

[[ 3  3  7]
 [ 2  4 10]
 [ 7  2  1]]
[3 2 1]
[2 2 1]
[13 16 10]
[63 80 14]


In [43]:
from numpy import *
random.seed(123)
arr=random.randint(1,15,15)
random.shuffle(arr)
print(unique(arr).size)
print(unique(arr,return_index=True,return_counts=True))
print(arr)

10
(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]), array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14], dtype=int64), array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))
[ 4  2 11 12 13  2  3  7  1  2  7  3 10 10 14]


In [48]:
from numpy import *
random.seed(123)
arr1=random.randint(1,20,9).reshape(3,3)
arr2=random.randint(20,40,9).reshape(3,3)
print(hstack((arr1,arr2)))
print(hstack((arr2,arr1)))
print(vstack((arr1,arr2)))

[[14  3  3 35 29 20]
 [ 7 18 11 34 20 35]
 [ 2  1 18 39 34 24]]
[[35 29 20 14  3  3]
 [34 20 35  7 18 11]
 [39 34 24  2  1 18]]
[[14  3  3]
 [ 7 18 11]
 [ 2  1 18]
 [35 29 20]
 [34 20 35]
 [39 34 24]]


In [1]:
from numpy import *
arr=array([1,2,3,4])
arr1=array([5,6,7,8])
print(hstack((arr,arr1)))
print(vstack((arr,arr1)))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
