### Numpy
NumPy is scientific computing library for python.

Support large number of data in the form of multi-dimensional array and matrix.

Use for mathematic calculation like linear algebra,Fourier transform and random number capabilities,etc.

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
# type of array
type(arr1)

numpy.ndarray

In [4]:
# dimension of array
arr1.ndim

1

In [5]:
arr2=np.array([[1,2,3,4],[5,6,7,8,]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
arr2.ndim

2

In [7]:
# array Size
arr1.size

5

In [8]:
# array size
arr2.size

8

In [9]:
# Array shape
arr1.shape

(5,)

In [10]:
# Array Shape row and colunm
arr2.shape

(2, 4)

In [11]:
# DataType
arr1.dtype

dtype('int32')

In [12]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Numpy methods

In [13]:
max1=np.array([[1,1,1],[1,1,1],[1,1,1]])
max1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
# ones function
max2=np.ones(5)
max2

array([1., 1., 1., 1., 1.])

In [15]:
max3=np.ones((5,5))
max3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
max4=np.ones(5)*5
max4

array([5., 5., 5., 5., 5.])

In [17]:
max5=np.ones((3,4),dtype=int)
max5
max5.dtype

dtype('int32')

In [18]:
max6=np.zeros((4,6))
print(max6)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
max6=np.zeros((4,6),dtype=bool)
print(max6)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [20]:
max6=np.zeros((4,6),dtype=str)
print(max6)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [21]:
# Convert str to bool
em_str=''
print(bool(em_str))

False


In [22]:
# empty function
em_max=np.empty((3,3))
em_max

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 6.976e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

### Numpy Function

In [23]:
import numpy as np

In [24]:
# arange( function)
#np.arange(start,end,steps)
arr_1=np.arange(1,13)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
ev_arr=np.arange(2,13,2)
ev_arr

array([ 2,  4,  6,  8, 10, 12])

In [26]:
# linespace function
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [27]:
# reshape function
arr_1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr_1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [29]:
ar=np.arange(1,13).reshape(2,6)
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [30]:
# ravel is conert array into 1d array
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
# flatten is used for
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
# transpose function is used for alternate the row and columns
ar1=ar.transpose()
ar1

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [33]:
ar1.T

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# Mathematic operation using Numpy

In [34]:
import numpy as np

In [35]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
display(arr1,arr2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [37]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [38]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [43]:
# dot multiplication
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [44]:
# simple multiplication
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [45]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [46]:
arr1.min()
arr1.max()

9

In [47]:
# maximum value matrix
arr1.argmax()

8

In [48]:
arr1.max(axis=1)

array([3, 6, 9])

In [49]:
arr1.max(axis=0)

array([7, 8, 9])

In [50]:
arr1.min()

1

In [51]:
# checking index
arr1.argmin()

0

In [52]:
arr1.min(axis=0)

array([1, 2, 3])

In [53]:
arr1.sum()

45

In [54]:
np.sum(arr1)

45

In [55]:
# columne addition
np.sum(arr1, axis=0)

array([12, 15, 18])

In [56]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [57]:
np.mean(arr1)

5.0

In [58]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [59]:
# standard devision
np.std(arr1)

2.581988897471611

In [60]:
# exponent
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [61]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [62]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

### String Operation, Comarisin and information

In [64]:
import numpy as np

In [65]:
ch_name="ABHIJIT Varpe"
str1='Learnig Python Numpy'

In [66]:
np.char.add(ch_name,str1)

array('ABHIJIT VarpeLearnig Python Numpy', dtype='<U33')

In [67]:
np.char.lower(ch_name)

array('abhijit varpe', dtype='<U13')

In [68]:
np.char.upper(str1)

array('LEARNIG PYTHON NUMPY', dtype='<U20')

In [70]:
np.char.center(str1,60)

array('                    Learnig Python Numpy                    ',
      dtype='<U60')

In [71]:
np.char.center(str1,60,fillchar="*")

array('********************Learnig Python Numpy********************',
      dtype='<U60')

In [72]:
np.char.split(ch_name)

array(list(['ABHIJIT', 'Varpe']), dtype=object)

In [73]:
np.char.splitlines('hello\nIndia')

array(list(['hello', 'India']), dtype=object)

In [74]:
str4='Dmy'
str5='Dmy'

In [75]:
np.char.join([':','/'],[str4,str5])

array(['D:m:y', 'D/m/y'], dtype='<U5')

In [76]:
np.char.replace(ch_name,'Varpe','VARPE')

array('ABHIJIT VARPE', dtype='<U13')

In [77]:
np.char.equal(str4,str5)

array(True)

In [78]:
np.char.count(ch_name,"A")

array(1)

In [79]:
ch_name

'ABHIJIT Varpe'

In [82]:
np.char.find(ch_name,"Va")

array(8)